CURSOR_SYMBOL_SELECTED="> "

CURSOR_SYMBOL_UNSELECTED="  "

CURSOR_SYMBOL=CURSOR_SYMBOL_SELECTED

ARROW_COLLAPSED="▸ "

ARROW_EXPANDED="▾ "

__all__=["CURSOR_SYMBOL_SELECTED","CURSOR_SYMBOL_UNSELECTED","CURSOR_SYMBOL","ARROW_COLLAPSED","ARROW_EXPANDED"]
